# Generated by Django 3.1.1 on 2021-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='Index',
            field=models.PositiveIntegerField(),
        ),
    ]
