# Generated by Django 3.1.1 on 2021-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0002_auto_20210317_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='ContentHeader',
            field=models.CharField(default='NoTitle', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='ContentText',
            field=models.CharField(max_length=1000),
        ),
    ]
