# Generated by Django 3.1.1 on 2021-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0003_auto_20210318_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecontent',
            name='ContentImageFile',
            field=models.ImageField(default='NoFile', upload_to='LectureImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='ContentImageTitle',
            field=models.CharField(default='NoTitle', max_length=100),
            preserve_default=False,
        ),
    ]
