# Generated by Django 3.1.1 on 2021-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0004_auto_20210318_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='ContentImageFile',
            field=models.ImageField(upload_to=''),
        ),
    ]
