# Generated by Django 3.1.1 on 2021-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0005_auto_20210318_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='ContentImageFile',
            field=models.ImageField(upload_to='static'),
        ),
    ]
