# Generated by Django 3.1.1 on 2021-03-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0006_auto_20210318_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturecontent',
            name='ContentHeader',
        ),
        migrations.RemoveField(
            model_name='lecturecontent',
            name='ContentImageFile',
        ),
        migrations.RemoveField(
            model_name='lecturecontent',
            name='ContentImageTitle',
        ),
        migrations.RemoveField(
            model_name='lecturecontent',
            name='ContentText',
        ),
        migrations.CreateModel(
            name='ImageContentModel',
            fields=[
                ('lecturecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LovelaceContentPage.lecturecontent')),
                ('ContentImageTitle', models.CharField(max_length=100)),
                ('ContentImageFile', models.ImageField(upload_to='static')),
            ],
            bases=('LovelaceContentPage.lecturecontent',),
        ),
        migrations.CreateModel(
            name='TextContentModel',
            fields=[
                ('lecturecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LovelaceContentPage.lecturecontent')),
                ('ContentText', models.CharField(max_length=1000)),
                ('ContentHeader', models.CharField(max_length=100)),
            ],
            bases=('LovelaceContentPage.lecturecontent',),
        ),
    ]
