# Generated by Django 3.1.1 on 2021-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0008_auto_20210322_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontentmodel',
            name='ContentImageTitle',
            field=models.CharField(max_length=100),
        ),
    ]
