# Generated by Django 3.1.1 on 2021-03-27 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0010_imagecontentmodel_contentimagecaption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContentModel',
            fields=[
                ('lecturecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LovelaceContentPage.lecturecontent')),
                ('ContentFileTitle', models.CharField(max_length=100)),
                ('ContentFile', models.FileField(upload_to='embeddedfiles')),
            ],
            bases=('LovelaceContentPage.lecturecontent',),
        ),
    ]
