# Generated by Django 3.1.1 on 2021-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0012_auto_20210327_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontentmodel',
            name='ContentTextNotParsed',
            field=models.CharField(default='update', max_length=1000),
            preserve_default=False,
        ),
    ]
