# Generated by Django 3.1.1 on 2021-04-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LovelaceContentPage', '0013_textcontentmodel_contenttextnotparsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedExerciseModel',
            fields=[
                ('lecturecontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LovelaceContentPage.lecturecontent')),
                ('ContentExerciseText', models.CharField(max_length=1000)),
                ('ContentExerciseTextNotParsed', models.CharField(max_length=1000)),
                ('ContentExerciseType', models.CharField(max_length=100)),
            ],
            bases=('LovelaceContentPage.lecturecontent',),
        ),
    ]
